apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-shadcn-data-table-helm
  namespace: pluaj-dev-dev
  labels:
    app: mi-app-dt-helm
    areanegocio: tecnologia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-dt-helm
  template:
    metadata:
      labels:
        app: mi-app-dt-helm
    spec:
      containers:
        - name: container-shadcn-data-table
          image: juangrp/shadcn-datatable-practica:build-20   # Ajusta si subes a Docker Hub
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"