apiVersion: v1
kind: Service
metadata:
  name: service-shadcn-data-table-helm
  namespace: pluaj-dev-dev  # Aseg√∫rate de que coincida con tu Deployment
spec:
  selector:
    app: mi-app-dt-helm
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP