apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.name }}
  namespace: {{ .Values.namespace }}  # Aseg√∫rate de que coincida con tu Deployment
spec:
  selector:
    app: {{ .Values.labels.app }}  # Debe coincidir con la etiqueta del Deployment
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}        # Puerto del Service
      targetPort: {{ .Values.container.port }}  # Puerto del contenedor
  type: ClusterIP